application: website-1007
version: 1
runtime: go
api_version: go1

skip_files:
- node_modules/.*
- ^(.*/)?.*\.un~$
- src/.*

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /
  static_dir: dist
- url: /go/*
  script: _go_app

